"""add pending verifications table

Revision ID: 369bdfc05c2d
Revises: 1bcbe7e42a47
Create Date: 2026-10-03 22:55:42.532744

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "369bdfc05c2d"
down_revision: str | None = "1bcbe7e42a47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: autogenerate also detected chat_messages.body's column type changing
    # to EncryptedText (server/models/encrypted_text.py) from an earlier,
    # unmigrated change - that's a SQLAlchemy-level type only (SQLite has no real
    # column-type enforcement to alter), so it's intentionally omitted here.
    op.create_table(
        "pending_verifications",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code_hash", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(
        op.f("ix_pending_verifications_user_id"),
        "pending_verifications",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pending_verifications_user_id"), table_name="pending_verifications")
    op.drop_table("pending_verifications")
    # ### end Alembic commands ###
