"""task completion time and work indexes

Autogenerated; the downgrade's drop_column was moved into batch mode.

Revision ID: 4cdf0ae0d428
Revises: b3dc54a36214
Create Date: 2026-09-30 19:37:01.775510

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cdf0ae0d428"
down_revision: str | None = "b3dc54a36214"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_projects_team_id"), "projects", ["team_id"], unique=False)
    op.create_index(op.f("ix_subtasks_assignee_id"), "subtasks", ["assignee_id"], unique=False)
    op.create_index(op.f("ix_subtasks_task_id"), "subtasks", ["task_id"], unique=False)
    op.add_column("tasks", sa.Column("completed_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_tasks_assignee_id"), "tasks", ["assignee_id"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assignee_id"), table_name="tasks")
    # Batch mode: SQLite only gained ALTER TABLE DROP COLUMN in 3.35, and the
    # Python on a teammate's Linux machine may ship an older SQLite.
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.drop_column("completed_at")
    op.drop_index(op.f("ix_subtasks_task_id"), table_name="subtasks")
    op.drop_index(op.f("ix_subtasks_assignee_id"), table_name="subtasks")
    op.drop_index(op.f("ix_projects_team_id"), table_name="projects")
    # ### end Alembic commands ###
