"""add lead and created_at to teams

Revision ID: b3dc54a36214
Revises: ea03b89dc9da
Create Date: 2026-09-30 19:12:26.102825

Autogenerated, then adjusted by hand for SQLite:

* ``batch_alter_table`` rebuilds the table, because SQLite's ALTER TABLE cannot
  add a NOT NULL column without a default, a CURRENT_TIMESTAMP default, or a
  foreign key.
* The foreign key is named, so the downgrade can drop it.
* ``uq_teams_name_lower`` is added by hand: autogenerate cannot see
  expression indexes on SQLite.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3dc54a36214"
down_revision: str | None = "ea03b89dc9da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Every team must have a lead, and there is no sensible lead to invent for
    # a team that already exists. No route could create teams before this
    # revision, so there should be none -- but fail loudly rather than guess.
    existing = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM teams")).scalar()
    if existing:
        raise RuntimeError(
            f"teams already has {existing} row(s) with no lead; "
            "delete them or assign leads by hand before upgrading"
        )

    with op.batch_alter_table("teams") as batch_op:
        batch_op.add_column(sa.Column("lead_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.create_index(batch_op.f("ix_teams_lead_id"), ["lead_id"], unique=False)
        batch_op.create_foreign_key("fk_teams_lead_id_users", "users", ["lead_id"], ["id"])

    op.create_index("uq_teams_name_lower", "teams", [sa.text("lower(name)")], unique=True)


def downgrade() -> None:
    op.drop_index("uq_teams_name_lower", table_name="teams")

    with op.batch_alter_table("teams") as batch_op:
        batch_op.drop_constraint("fk_teams_lead_id_users", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_teams_lead_id"))
        batch_op.drop_column("created_at")
        batch_op.drop_column("lead_id")
