"""add two_factor_enabled to users

Revision ID: ea03b89dc9da
Revises: 369bdfc05c2d
Create Date: 2026-10-04 00:52:55.159810

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea03b89dc9da"
down_revision: str | None = "369bdfc05c2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: autogenerate also detected chat_messages.body's column type (now
    # EncryptedText, see server/models/encrypted_text.py) from an earlier,
    # unmigrated change - intentionally omitted, same as the prior migration
    # (SQLite has no real column-type enforcement to alter).
    op.add_column(
        "users",
        sa.Column("two_factor_enabled", sa.Boolean(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "two_factor_enabled")
    # ### end Alembic commands ###
